name: image-publisher

on:
  workflow_dispatch:
    inputs:
      REGISTRY_NAMESPACE:
        required: true
        default: ocs
      IMAGE_TAG:
        required: true
        default: latest

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push docker images
      env:
        REGISTRY_NAMESPACE: ${{ github.event.inputs.REGISTRY_NAMESPACE }}
        IMAGE_TAG: ${{ github.event.inputs.IMAGE_TAG }}
        IMAGE_REGISTRY: ghcr.io/teamziax
      run: |
        make docker-build docker-push
        make bundle-build bundle-push
        make catalog-build catalog-push
